steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/election66/election66-blind-test:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/election66/election66-blind-test:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'election66-blind-test-cloud-run', '--image', 'gcr.io/election66/election66-blind-test:latest', '--region', 'asia-east1']
images:
- gcr.io/election66/election66-blind-test:latest

